function createRuntimeInitDeps(deps) {
    const {
        getConfig,
        getScene,
        getSceneStateInitDone,
        setSceneState,
        resetViewTransformState,
        initRepeatButtons,
        d3SelectAll,
        setChecked,
        bindRepeatButtons,
        d3Select,
        getHandlersById,
        getTimeoutHandleZoom,
        setTimeoutHandleZoom,
        setMousedownTimeout,
        setMouseDown,
        getZoomTimeoutMs,
        clearTimeoutFn,
        zoomEnd,
        sleep,
        setAnimDate,
        getCurrentDimension,
        initSVG,
        loadOrbitDataIfNeededAndProcess,
        loadLandingDataAndProcess,
    } = deps;

    return {
        getConfig,
        getScene,
        getSceneStateInitDone,
        setSceneState,
        resetViewTransformState,
        initRepeatButtons,
        d3SelectAll,
        setChecked,
        bindRepeatButtons,
        d3Select,
        getHandlersById,
        getTimeoutHandleZoom,
        setTimeoutHandleZoom,
        setMousedownTimeout,
        setMouseDown,
        getZoomTimeoutMs,
        clearTimeoutFn,
        zoomEnd,
        sleep,
        setAnimDate,
        getCurrentDimension,
        initSVG,
        loadOrbitDataIfNeededAndProcess,
        loadLandingDataAndProcess,
    };
}

function createRuntimeUiControlsDeps(deps) {
    const {
        createNavigationActions,
        createRepeatMouseDownHandlers,
        createLockActions,
        createCameraActions,
        createModeActions,
        createMoonRenderProfileActions,
        createMoonRenderPipelineActions,
        createBurnActions,
        getConfig,
        getPanXState,
        setPanXState,
        getPanYState,
        setPanYState,
        getZoomFactorState,
        setZoomFactorState,
        zoomChange,
        zoomEnd,
        render,
        getZoomTimeoutMs,
        getZoomScale,
        toggleStatsVisibility,
        forward,
        fastForward,
        backward,
        fastBackward,
        slower,
        resetspeed,
        faster,
        realtime,
        getMouseDownTimeout,
        setMouseDownTimeout,
        setTimeoutHandleZoom,
        animationScenes,
        setChecked,
        readCameraPositionMode,
        readCameraLookMode,
        applyCameraFromTo,
        readPlaneSelection,
        setPlaneSelectionState,
        handlePlaneChange,
        applyViewForCurrentIdentity,
        getViewSky,
        getViewConstellationLines,
        getGlobalConfig,
        updateCraftScale,
        getLandingFlag,
        setLandingFlag,
        getJoyRideFlag,
        setJoyRideFlag,
        setView,
        getEventInfos,
        getTimelineEventInfos,
        setAnimTime,
        missionSetTime,
        THREE,
        loadSceneTextures,
        loadMoonRenderProfileTextures,
        applyAndRefreshSceneTextures,
        globalObject,
    } = deps;

    return {
        createNavigationActions,
        createRepeatMouseDownHandlers,
        createLockActions,
        createCameraActions,
        createModeActions,
        createMoonRenderProfileActions,
        createMoonRenderPipelineActions,
        createBurnActions,
        getPanX: () => getPanXState(getConfig()),
        setPanX: (val) => {
            setPanXState(val, getConfig());
        },
        getPanY: () => getPanYState(getConfig()),
        setPanY: (val) => {
            setPanYState(val, getConfig());
        },
        getZoomFactor: () => getZoomFactorState(getConfig()),
        setZoomFactor: (val) => {
            setZoomFactorState(val, getConfig());
        },
        zoomChange,
        zoomEnd,
        render,
        getZoomTimeoutMs,
        getZoomScale,
        toggleStatsVisibility,
        forward,
        fastForward,
        backward,
        fastBackward,
        slower,
        resetspeed,
        faster,
        realtime,
        getMouseDownTimeout,
        setMouseDownTimeout,
        setTimeoutHandleZoom,
        animationScenes,
        getConfig,
        setChecked,
        readCameraPositionMode,
        readCameraLookMode,
        applyCameraFromTo,
        readPlaneSelection,
        setPlaneSelection: (val) => {
            setPlaneSelectionState(val, getConfig());
        },
        handlePlaneChange,
        applyViewForCurrentIdentity,
        getViewSky,
        getViewConstellationLines,
        getGlobalConfig,
        updateCraftScale,
        getLandingFlag,
        setLandingFlag,
        getJoyRideFlag,
        setJoyRideFlag,
        setView,
        getEventInfos,
        getTimelineEventInfos,
        setAnimTime,
        missionSetTime,
        THREE,
        loadSceneTextures,
        loadMoonRenderProfileTextures,
        applyAndRefreshSceneTextures,
        globalObject,
    };
}

export {
    createRuntimeInitDeps,
    createRuntimeUiControlsDeps,
};
